name = "dns"
main = "./dist/worker.js"
workers_dev = true
# logpush job is setup to capture from envs ending: log, pro, or one
logpush = false
# use node_compat or custom build
# node_compat = true
compatibility_date = "2022-11-30"
send_metrics = false
minify = false

# uncomment to enable analytics on serverless-dns
# this binding is not inherited by other worker-envs
#analytics_engine_datasets = [
#    { binding = "METRICS", dataset = "SDNS_M0" },
#    { binding = "BL_METRICS", dataset = "SDNS_BL0" }
#]

[build]
command = "npm run build"

[[rules]]
type = "ESModule"
globs = ["**/*.js"]

[vars]
LOG_LEVEL = "debug"
WORKER_ENV = "development"
CLOUD_PLATFORM = "cloudflare"
CF_DNS_RESOLVER_URL = "168.138.47.214"

##################
#------PROD------#
##################
# wrangler doesn't yet support Workers Services and the new "Environments"
# github.com/cloudflare/cloudflare-docs/pull/3175/files
# github.com/cloudflare/wrangler2/issues/27
# developers.cloudflare.com/workers/platform/environments
[env.prod]
name = "basic-unbound"
minify = true
routes = [
  "sky.rethinkdns.com/*",
  "sky.bravedns.com/*",
  "basic.rethinkdns.com/*",
  "basic.bravedns.com/*",
  "free.bravedns.com/*",
]
# vars are not inherited
# workers/platform/environment-variables#environment-variables-via-wrangler
[env.prod.vars]
LOG_LEVEL = "info"
WORKER_ENV = "production"
CLOUD_PLATFORM = "cloudflare"
CF_DNS_RESOLVER_URL = "dns.neko2.org:4443/dns-query"

##################
#------ONE-------#
##################
[env.one]
name = "dns-one"
logpush = true
minify = true
routes = [
  "one.rethinkdns.com/*",
  "one.bravedns.com/*",
]
analytics_engine_datasets = [
    { binding = "METRICS", dataset = "ONE_M0" },
    { binding = "BL_METRICS", dataset = "ONE_BL0" }
]

[env.one.vars]
# just the error and request logs
LOG_LEVEL = "logpush"
WORKER_ENV = "production"
CLOUD_PLATFORM = "cloudflare"
CF_LOGPUSH_R2_PATH = "qlog/"
CF_DNS_RESOLVER_URL = "dns.neko2.org:4443/dns-query"

##################
#-----SECRETS----#
##################
# only for documentation purposes
# developers.cloudflare.com/workers/platform/environment-variables/#adding-secrets-via-wrangler
# [secrets]
# GW_IP4 = ""
# GW_IP6 = ""
# CF_ACCOUNT_ID = ""
# CF_API_TOKEN = ""
# CF_LOGPUSH_R2_SECRET_KEY = ""
# CF_LOGPUSH_R2_ACCESS_KEY = ""
